### PR TITLE
feat: RulesEngine Optimization

### PR DESCRIPTION
**Pull request by mfranceschit**
Performance increased drastically, reducing the number of mutations. from 362 mutations in 10.379s  to 4 mutations in 3.381s

Also, the redundant data in the mutations data was optimized to decrease the payload size.

Depends on https://github.com/cloudgraphdev/cloudgraph-provider-aws/pull/4
Depends on https://github.com/cloudgraphdev/cloudgraph-policy-packs/pull/1

### CODE REVIEW

**Review by hjaraujof — APPROVED** [review]

**Review by m-pizarro — APPROVED** [review]

**Comment by tyler-dunkel** [comment]
@mfranceschit are any changes needed here with the latest updates from the aws pr?

**Comment by mfranceschit** [comment]
> @mfranceschit are any changes needed here with the latest updates from the aws pr?

No, this works as is. Although, we should wait before merge until the latest policy packs changes + aws provider changes arrive on `main`

**Comment by tyler-dunkel** [comment]
> > @mfranceschit are any changes needed here with the latest updates from the aws pr?
> 
> No, this works as is. Although, we should wait before merge until the latest policy packs changes + aws provider changes arrive on `main`

to merge to main or even to merge to alpha?

**Comment by mfranceschit** [comment]
> > > @mfranceschit are any changes needed here with the latest updates from the aws pr?
> > 
> > 
> > No, this works as is. Although, we should wait before merge until the latest policy packs changes + aws provider changes arrive on `main`
> 
> to merge to main or even to merge to alpha?

Well, sure, we can start working when the latest changes to the policy packs reach at least `alpha`. But, if we set this SDK version at the CLI and don't specify that we are using provider@alpha and policypack@alpha it won't work as expected because all those changes should be in place before merging. That's why I prefer to have those on `main`.

**Pull request merged**
